replicaCount: 1

image:
  repository: <your-dockerhub>/archival-service
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

# -- (map) Postgres database configuration. If db does not exist in postgres cluster and dbCreate is set ot true then these databases will be created for you
postgres:
  # (bool) Whether the database should be restored from s3. Default to global.postgres.dbRestore
  dbRestore: false
  # -- (bool) Whether the database should be created. Default to global.postgres.dbCreate
  dbCreate:
  # -- (string) Hostname for postgres server. This is a service override, defaults to global.postgres.host
  host: gen3-postgresql
  # -- (string) Database name for postgres. This is a service override, defaults to <serviceName>-<releaseName>
  database: archival-service-1
  # -- (string) Username for postgres. This is a service override, defaults to <serviceName>-<releaseName>
  username: archival-service-1
  # -- (string) Port for Postgres.
  port: "5432"
  # -- (string) Password for Postgres. Will be autogenerated if left empty.
  password: password
  # -- (string) Will create a Database for the individual service to help with developing it.
  separate: false
