location /archival-service/ {

    set $proxy_service  "archival-service";
    set $upstream http://archival-service$des_domain;

    rewrite ^/archival-service/(.*) /$1 break;

    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/archival-service/;

    client_max_body_size 0;
}
