location /matt-tes/ {

    set $proxy_service  "matt-tes";
    set $upstream http://matt-tes$des_domain;

    rewrite ^/matt-tes/(.*) /$1 break;

    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/matt-tes/;

    client_max_body_size 0;
}
