location /pub-sub/ {

    set $proxy_service  "pub-sub";
    set $upstream http://pub-sub$des_domain;

    rewrite ^/pub-sub/(.*) /$1 break;

    proxy_pass $upstream;
    proxy_redirect http://$host/ https://$host/pub-sub/;

    client_max_body_size 0;
}
